### ISSUE TITLE
Semáforo para pedestres 

### ISSUE THREAD

**Issue by TakiDS** [felipesantos10/semaforo#1]
Tive uma idéia que pode enriquecer o projeto e estimular ainda mais os estudantes. Adicionar um segundo semáforo para pedestres que esteja conectado ao semáforo, indicando se a travessia de pedestres está permitida na rua, com um alerta dizendo se é "sinal aberto" ou "sinal fechado, aguarde". Além disso, adicionar um botão que antecipe a abertura do sinal para pedestres, fechando o semáforo para os veículos.

![image](https://github.com/felipesantos10/semaforo/assets/167918424/9f2d1d5b-f48b-4b6c-9835-88247ab18e4d)

Para implementar isso, você precisaria adicionar um novo estado ao sinal do semáforo para pedestres e criar um conjunto separado de regras para o sinal do pedestre. Além disso, você precisaria adicionar um botão que dispare a mudança de estado do semáforo, permitindo que os pedestres atravessem a rua. Isso exigiria algumas modificações, mas seria uma adição valiosa ao projeto.

**Comment by felipesantos10** [comment]
Excelente adição. Não Havia pensado nisso quando fiz esse projeto. 
Vou aderir mais as= frentes as suas observações e fazer os ajustes para integrar essas modificações.

Obrigado @TakiDS
